git_repo: git@github.com:endpoints/endpoints.git
base_path: /mnt
site_path: "{{base_path}}/site"
clone_path: "{{base_path}}/temp"
public_path: "{{site_path}}/website"

site_user: www-data
site_group: www-data
site_port: 8080
site_log_file: /var/log/site

users:
  - name: ag_dubs
    real_name: Ashley Williams
    state: present
    shadow_pass: $1$poopsalo$leTBLi1qiudh69.gIeaF/0
    groups: sudo
    shell: /bin/bash
    keys:
      - state: present
        key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDn6RKYQrau3fOgzcIumuQcxvpfs6xrueXv+r5Es/yowPpub9UcLaeJWHSgapv70+jdj3Z4molXvyeDifu6G5hE/89bJTkIJ8eFYGryRpJmwT7hnnJHSgZWJu62zcLbVGhGoNwTP1d4ah8rBgvd5rt4MZobLZa2MiTteLU9krDVUJuPMjLFN9kyjwWRPFt9F+HY3JltOJbg2kyJZBpijy9idxDs++AJ37IJiXlbykn7gylR9JWoTaagGXkPZPtGQ4r9gF9mAUsSqU1JTaLG3HpXVrxgCQEWbAbRDs7z7GJ1mqN0h6/XVwyQpBvgBVk8VJRlZ+Wll9a80+Q/NH5qau8v ashley@bocoup.com
